(ns resolver-sim.pro-rata.protocol-realization
  "Protocol adapter conformance for a canonical effect transition.

   A realization proves projection/reconstruction equivalence *and* a frame
   condition: protocol fields outside the adapter-authorized write set cannot
   change merely because they are omitted from the canonical projection."
  (:require [resolver-sim.hash.canonical :as hc]
            [resolver-sim.pro-rata.canonical-effects :as effects]))

(def adapter-schema "protocol-effect-adapter-identity.v1")
(def realization-schema "protocol-effect-realization.v1")

(defn adapter-root [adapter]
  (hc/domain-hash :protocol-effect-adapter-identity
                  (select-keys adapter [:schema-version :protocol/id
                                        :protocol-state-schema/root
                                        :projection-semantics/root
                                        :quantity-mapping/root
                                        :reconstruction-semantics/root
                                        :write-set-semantics/root])))

(defn build-adapter
  [{:keys [protocol-id protocol-state-schema-root projection-semantics-root
           quantity-mapping-root reconstruction-semantics-root
           write-set-semantics-root] :as adapter}]
  (when-not (and (keyword? protocol-id)
                 (every? string? [protocol-state-schema-root projection-semantics-root
                                  quantity-mapping-root reconstruction-semantics-root
                                  write-set-semantics-root]))
    (throw (ex-info "incomplete protocol effect adapter identity" {:adapter adapter})))
  (let [base {:schema-version adapter-schema
              :protocol/id protocol-id
              :protocol-state-schema/root protocol-state-schema-root
              :projection-semantics/root projection-semantics-root
              :quantity-mapping/root quantity-mapping-root
              :reconstruction-semantics/root reconstruction-semantics-root
              :write-set-semantics/root write-set-semantics-root}]
    (assoc base :adapter/root (adapter-root base))))

(defn write-set-root [paths]
  (hc/domain-hash :protocol-effect-write-set
                  {:schema-version "protocol-effect-write-set.v1"
                   :paths (vec (sort paths))}))

(defn- path-authorized? [write-path path]
  (and (<= (count write-path) (count path))
       (= write-path (subvec (vec path) 0 (count write-path)))))

(defn- changed-paths [before after]
  (letfn [(walk [path left right]
            (cond
              (= left right) []
              (and (map? left) (map? right))
              (mapcat (fn [key] (walk (conj path key) (get left key) (get right key)))
                      (sort (into #{} (concat (keys left) (keys right)))))
              :else [path]))]
    (vec (walk [] before after))))

(defn frame-valid?
  "All changed protocol paths must be under one adapter-authorized write path."
  [protocol-before protocol-after write-set]
  (every? (fn [path] (some #(path-authorized? % path) write-set))
          (changed-paths protocol-before protocol-after)))

(defn realization-root [realization]
  (hc/domain-hash :protocol-effect-realization
                  (select-keys realization [:schema-version :protocol/id :adapter/root
                                            :canonical-transition/root
                                            :protocol-state-before/root
                                            :canonical-state-before/root
                                            :canonical-state-after/root
                                            :protocol-state-after/root
                                            :write-set/root
                                            :realization-semantics/root])))

(defn build-realization
  "Derive a protocol realization from real data and adapter functions.

   `project` maps protocol state to the complete canonical quantity state;
   `reconstruct` receives protocol-before, canonical-after, and write-set.
   The supplied canonical transition must be one generated by canonical-effects.
   Authorization is deliberately outside this semantic boundary."
  [{:keys [adapter canonical-transition protocol-before write-set project reconstruct
           protocol-state-root realization-semantics-root]}]
  (when-not (and (= adapter-schema (:schema-version adapter))
                 (= (:adapter/root adapter) (adapter-root adapter))
                 (fn? project) (fn? reconstruct) (fn? protocol-state-root)
                 (vector? write-set) (string? realization-semantics-root))
    (throw (ex-info "invalid protocol realization inputs" {})))
  (let [canonical-before (project protocol-before)
        expected-before (:state-before/root canonical-transition)
        expected-after (:state-after/root canonical-transition)
        _ (when-not (= expected-before (effects/state-root canonical-before))
            (throw (ex-info "protocol projection does not match canonical transition before-state" {})))
        protocol-after (reconstruct protocol-before (:state-after canonical-transition) write-set)
        canonical-after (project protocol-after)
        _ (when-not (= expected-after (effects/state-root canonical-after))
            (throw (ex-info "protocol reconstruction does not project to canonical transition after-state" {})))
        _ (when-not (frame-valid? protocol-before protocol-after write-set)
            (throw (ex-info "protocol reconstruction violated adapter frame condition"
                            {:changed-paths (changed-paths protocol-before protocol-after)})))
        base {:schema-version realization-schema
              :protocol/id (:protocol/id adapter)
              :adapter/root (:adapter/root adapter)
              :canonical-transition/root (hc/domain-hash :canonical-effect-transition
                                                         (select-keys canonical-transition [:schema-version :effect-semantics/root :state-before/root :effects/root :state-after/root]))
              :protocol-state-before/root (protocol-state-root protocol-before)
              :canonical-state-before/root expected-before
              :canonical-state-after/root expected-after
              :protocol-state-after/root (protocol-state-root protocol-after)
              :write-set/root (write-set-root write-set)
              :realization-semantics/root realization-semantics-root}]
    (assoc base :protocol-effect-realization/root (realization-root base))))
