#!/usr/bin/env clojure
(ns scripts.generate-public-headline-claims
  "Validates the public headline-claim registry and generates its public copy."
  (:require [clojure.edn :as edn]
              [clojure.java.io :as io]
              [clojure.string :as str]
              [resolver-sim.benchmark.claims :as benchmark-claims])
  (:import [java.math BigInteger]
           [java.nio.charset StandardCharsets]
           [java.security MessageDigest]))

(def registry-path "benchmarks/public-headline-claims.edn")
(def output-path "docs/generated/public-headline-claims.md")
(def sha256-pattern #"[0-9a-f]{64}")

(defn sha256 [value]
  (format "%064x" (BigInteger. 1 (.digest (MessageDigest/getInstance "SHA-256")
                                            (.getBytes (str value) StandardCharsets/UTF_8)))))

(defn fail! [message]
  (throw (ex-info (str "[public-headline-claims] " message) {})))

(defn valid-sha? [value]
  (boolean (and (string? value) (re-matches sha256-pattern value))))

(defn- benchmark-manifests []
  (into {}
        (keep (fn [file]
                (let [manifest (edn/read-string (slurp file))]
                  (when-let [benchmark-id (:benchmark/id manifest)]
                    [benchmark-id manifest]))))
        (filter #(.isFile ^java.io.File %)
                (file-seq (io/file "benchmarks/packs")))))

(defn- declared-claim? [manifest claim-id]
  (some #(= claim-id (:claim/id %)) (:benchmark/claims manifest)))

(defn validate-claim! [manifests claim]
  (doseq [key [:claim/id :claim/version :publication/status :claim/text :claim/scope
               :claim/assumptions :benchmark/claims :evaluator/id :evaluator/version :evaluator/implementation
               :policy/canonical-edn :policy/sha256 :evidence/packages :publication/copy]]
    (when-not (contains? claim key)
      (fail! (str (:claim/id claim) " is missing " key))))
  (when-not (and (string? (:claim/id claim)) (re-matches #"PHC-[0-9]{4}" (:claim/id claim)))
    (fail! (str "invalid stable public claim ID: " (:claim/id claim))))
  (let [{:keys [path] implementation-sha :sha256} (:evaluator/implementation claim)]
    (when-not (.exists (io/file path))
      (fail! (str (:claim/id claim) " evaluator source is missing: " path)))
    (when-not (= implementation-sha (sha256 (slurp path)))
      (fail! (str (:claim/id claim) " evaluator implementation hash does not match " path))))
  (when-not (benchmark-claims/evaluator-resolver (:evaluator/id claim))
    (fail! (str (:claim/id claim) " references an unregistered evaluator " (:evaluator/id claim))))
  (doseq [{:benchmark/keys [id] :keys [claims]} (:benchmark/claims claim)]
    (when-not (and id (seq claims))
      (fail! (str (:claim/id claim) " has an invalid benchmark claim binding")))
    (let [manifest (get manifests id)]
      (when-not manifest
        (fail! (str (:claim/id claim) " references unknown benchmark " id)))
      (doseq [claim-id claims]
        (when-not (declared-claim? manifest claim-id)
          (fail! (str (:claim/id claim) " references undeclared claim " claim-id " in " id)))
        (when-not (= claim-id (:evaluator/id claim))
          (fail! (str (:claim/id claim) " evaluator must match bound claim " claim-id))))))
  (when-not (= (:policy/sha256 claim) (sha256 (:policy/canonical-edn claim)))
    (fail! (str (:claim/id claim) " policy hash does not match canonical policy text")))
  (when (= :published (:publication/status claim))
    (when (empty? (:evidence/packages claim))
      (fail! (str (:claim/id claim) " is public but has no immutable evidence package")))
    (doseq [{:keys [uri sha256]} (:evidence/packages claim)]
      (when-not (and (string? uri) (valid-sha? sha256))
        (fail! (str (:claim/id claim) " has an invalid immutable evidence package reference"))))))

(defn render [claims]
  (let [published (filter #(= :published (:publication/status %)) claims)]
    (str "<!-- public-claims: registry; generated by scripts/generate_public_headline_claims.clj from benchmarks/public-headline-claims.edn. Do not edit. -->\n"
         "## Public Benchmark Claims\n\n"
         "Public headline copy is generated from the versioned [headline-claim registry](../../benchmarks/public-headline-claims.edn). "
         "Every published claim is bound to an evaluator implementation hash, policy hash, and immutable evidence-package reference.\n\n"
         (if (seq published)
           (str "| Claim ID | Headline | Public copy |\n|---|---|---|\n"
                (apply str (for [{:claim/keys [id] :publication/keys [copy]} published]
                             (str "| `" id "` | " (:headline copy) " | " (:summary copy) " |\n"))))
           "No public headline claims are currently published. Registry entries remain draft until a qualifying evidence package is committed or otherwise published with a SHA-256 reference.\n")
         "\n### Publication rule\n\n"
         "A claim is rendered only at `:published` status. Validation rejects a published entry whose evaluator source hash or policy hash has drifted, or that lacks a package URI and SHA-256.\n")))

(defn -main [& _]
  (let [registry (edn/read-string (slurp registry-path))
        claims (:claims registry)
        manifests (benchmark-manifests)]
    (when-not (= 1 (:public-headline-claim-registry/version registry))
      (fail! "unsupported registry version"))
    (when-not (= (count claims) (count (distinct (map :claim/id claims))))
      (fail! "duplicate public claim ID"))
    (doseq [claim claims] (validate-claim! manifests claim))
    (spit output-path (render claims))
    (println "[public-headline-claims] PASS:" (count claims) "entries validated;" (count (filter #(= :published (:publication/status %)) claims)) "published")))
