---
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Reload PostgreSQL
  systemd:
    name: postgresql
    state: reloaded

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted

- name: Systemctl daemon-reload
  systemd:
    daemon_reload: yes
